# Generated by Django 6.0.5 on 2026-05-16 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст статті')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва страви')),
                ('category', models.CharField(choices=[('Diet Recipes', 'Diet Recipes (Схуднення)'), ('Gaining Mass', 'Gaining Mass (Набір маси)'), ('Recovery', 'Recovery Recipes (Відновлення)')], max_length=20, verbose_name='Категорія')),
                ('prep_time', models.IntegerField(verbose_name='Час приготування (хв)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва продукту')),
                ('weight', models.FloatField(verbose_name='Вага (г)')),
                ('calories', models.FloatField(verbose_name='Калорії')),
                ('protein', models.FloatField(verbose_name='Білки')),
                ('fat', models.FloatField(verbose_name='Жири')),
                ('carbs', models.FloatField(verbose_name='Вуглеводи')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
        ),
    ]
