# Generated by Django 6.0.5 on 2026-05-17 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_post_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Ріст (см)')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Вага (кг)')),
                ('sport_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вид спорту')),
                ('daily_calories', models.IntegerField(blank=True, null=True, verbose_name='Денна норма калорій')),
                ('saved_recipes', models.ManyToManyField(blank=True, related_name='saved_by', to='recipes.recipe', verbose_name='Збережені рецепти')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
    ]
